from __future__ import annotations


TERM_GUIDES = {
    "chest": {
        "Input fields": {
            "Chest X-ray image": "A chest radiograph image used by the model to look for patterns linked to lung and chest conditions.",
            "Patient age": "Age in years. It gives extra clinical context to the model.",
            "Patient gender": "Recorded sex/gender field used as metadata context. If unknown, use the Unknown option.",
            "View position": "How the X-ray was taken. PA means posteroanterior view and AP means anteroposterior view.",
            "Follow-up count": "How many times the same patient has been imaged or followed in the dataset context.",
        },
        "Output terms": {
            "Pneumonia probability": "The model score for the pneumonia label. Higher means the model sees stronger evidence for pneumonia-related patterns.",
            "Primary decision": "The final text summary returned by the model after comparing each label score with its threshold.",
            "Predicted findings": "Labels whose probabilities crossed their tuned thresholds.",
            "Threshold": "A cutoff value used to convert a probability into a positive or negative finding.",
            "Grad-CAM": "A visual heatmap showing which image regions influenced the model most strongly for a chosen label.",
            "No finding above threshold": "The model did not push any label above its selected decision cutoff.",
        },
        "Chest labels": {
            "Atelectasis": "Partial collapse or incomplete expansion of part of the lung.",
            "Cardiomegaly": "Enlarged heart shadow or enlarged heart size on imaging.",
            "Consolidation": "Region where normal air in the lung is replaced by fluid, pus, blood, or cells.",
            "Edema": "Fluid buildup in lung tissue, often described as pulmonary edema.",
            "Effusion": "Fluid around the lungs in the pleural space.",
            "Emphysema": "Damage to air sacs in the lungs leading to over-inflation and reduced breathing efficiency.",
            "Fibrosis": "Scarring of lung tissue.",
            "Hernia": "A protrusion of tissue or an organ through a structure that normally contains it.",
            "Infiltration": "A broad imaging term suggesting abnormal material or opacity within the lung.",
            "Mass": "A larger abnormal lump or growth seen on imaging.",
            "Nodule": "A small rounded spot or lesion seen in the lung.",
            "Pleural Thickening": "Thickening of the lining around the lungs.",
            "Pneumonia": "Lung infection or inflammation that can cause opacity on chest imaging.",
            "Pneumothorax": "Air in the pleural space causing partial or full lung collapse.",
        },
    },
    "skin": {
        "Input fields": {
            "Lesion image": "A skin lesion photo or dermoscopic image used for classification.",
            "Age": "Patient age in years used as context for lesion prediction.",
            "Sex": "Patient sex field used as metadata context.",
            "Localization": "Body location of the lesion such as back, face, trunk, or lower extremity.",
        },
        "Output terms": {
            "Top class": "The lesion class with the highest predicted probability.",
            "Top probability": "The model confidence for the highest-ranked lesion class.",
            "Malignant-risk proxy": "A simple combined score based on selected lesion classes associated with more serious disease patterns.",
            "Grad-CAM": "A visual heatmap showing which lesion regions influenced the image model most strongly.",
        },
        "Skin classes": {
            "akiec": "Actinic keratoses and intraepithelial carcinoma. These are sun-damage related lesions that can be clinically important.",
            "bcc": "Basal cell carcinoma, a common form of skin cancer.",
            "bkl": "Benign keratosis-like lesions, usually non-cancerous growth patterns.",
            "df": "Dermatofibroma, a usually benign fibrous skin lesion.",
            "mel": "Melanoma, a serious type of skin cancer.",
            "nv": "Melanocytic nevus, commonly a mole.",
            "vasc": "Vascular lesion, involving blood vessel-related skin changes.",
        },
    },
    "diabetes": {
        "Input fields": {
            "Pregnancies": "Number of pregnancies recorded for the patient.",
            "Glucose": "Plasma glucose concentration. Higher values can be associated with diabetes risk.",
            "BloodPressure": "Diastolic blood pressure measurement in mm Hg.",
            "SkinThickness": "Triceps skin fold thickness, often used as a body-fat related measure in this dataset.",
            "Insulin": "Two-hour serum insulin value in the dataset.",
            "BMI": "Body Mass Index, usually calculated as weight in kilograms divided by height in meters squared.",
            "DiabetesPedigreeFunction": "A dataset-specific score intended to reflect family history or inherited tendency toward diabetes.",
            "Age": "Patient age in years.",
        },
        "Output terms": {
            "Diabetes probability": "The calibrated model probability for the diabetes class.",
            "Decision threshold": "The cutoff used to decide whether the model predicts diabetes or no diabetes.",
            "Primary decision": "The final class label after thresholding the probability.",
            "Feature contribution": "How much each input feature pushed the prediction higher or lower for the current case.",
        },
    },
    "heart": {
        "Input fields": {
            "BMI": "Body Mass Index. Use the calculator in the page if you know height and weight.",
            "Smoking": "Whether the patient is recorded as a smoker.",
            "AlcoholDrinking": "Whether the patient reports heavy alcohol drinking in the dataset context.",
            "Stroke": "Whether the patient has a history of stroke.",
            "PhysicalHealth": "Number of days in the last 30 days when physical health was not good.",
            "MentalHealth": "Number of days in the last 30 days when mental health was not good.",
            "DiffWalking": "Whether the patient reports difficulty walking or climbing stairs.",
            "Sex": "Recorded sex field in the dataset.",
            "AgeCategory": "Age grouped into a predefined age range.",
            "Race": "Race or ethnicity category recorded in the survey dataset.",
            "Diabetic": "Diabetes status category reported in the dataset.",
            "PhysicalActivity": "Whether the patient reports physical activity outside regular job activity.",
            "GenHealth": "Self-rated general health from poor to excellent.",
            "SleepTime": "Average hours of sleep per day.",
            "Asthma": "Whether the patient reports asthma.",
            "KidneyDisease": "Whether the patient reports kidney disease.",
            "SkinCancer": "Whether the patient reports a history of skin cancer.",
        },
        "Output terms": {
            "Heart disease probability": "The calibrated model probability for the heart disease class.",
            "Decision threshold": "The cutoff used to convert the heart-risk probability into the final decision.",
            "Primary decision": "The final class after thresholding the probability.",
            "Feature contribution": "How much each survey or clinical field pushed the prediction higher or lower for this case.",
        },
    },
    "evaluation": {
        "Metrics and terms": {
            "Accuracy": "The fraction of predictions that were correct overall.",
            "Balanced accuracy": "Average recall across classes. Useful when classes are imbalanced.",
            "Precision": "Of the positive predictions made, how many were actually positive.",
            "Recall": "Of the actual positive cases, how many the model found.",
            "F1 score": "A balance between precision and recall.",
            "Macro F1": "F1 averaged equally across classes or labels.",
            "Weighted F1": "F1 averaged across classes but weighted by class size.",
            "ROC-AUC": "Area under the ROC curve. Measures ranking quality across thresholds.",
            "PR-AUC": "Area under the precision-recall curve. Often more informative for imbalanced data.",
            "Macro ROC-AUC": "ROC-AUC averaged equally across labels or classes.",
            "Micro ROC-AUC": "ROC-AUC computed by pooling all predictions together.",
            "Macro PR-AUC": "Precision-recall AUC averaged equally across labels or classes.",
            "Micro PR-AUC": "Precision-recall AUC computed using pooled predictions.",
            "Threshold": "Probability cutoff used to turn scores into predicted classes or findings.",
            "Candidate scores": "Validation scores for multiple model candidates before the final one was chosen.",
            "Model comparison": "Side-by-side evaluation of candidate models or ablation variants.",
            "Ablation": "A comparison between versions of the system, such as image-only versus metadata fusion.",
            "Calibration": "Adjustment so predicted probabilities better match observed outcomes.",
            "Experiment history": "Saved record of past training runs, settings, and model versions.",
            "Raw metrics payload": "The full stored metrics dictionary behind the summary view.",
        },
    },
    "history": {
        "History terms": {
            "Prediction history": "Saved list of past predictions made in the app.",
            "Session": "A user-created group that lets multiple predictions be collected under one case or demo flow.",
            "Module": "Which analysis pipeline created the prediction, such as Chest X-ray or Diabetes.",
            "Decision": "The final predicted class or text summary returned by the model.",
            "Model": "The chosen trained model or variant used for that prediction.",
            "Created": "The timestamp when the prediction was stored.",
            "Session ID": "Numeric identifier used to group predictions together.",
            "Combined session report": "A downloadable HTML report that merges all saved predictions from one session.",
            "Visible records": "The number of history rows currently shown after filtering.",
        },
    },
}
